# Generated by Django 5.0.3 on 2024-03-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
