# Generated by Django 5.0.3 on 2024-03-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
