# Generated by Django 5.0.3 on 2024-04-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_age_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
