# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_News', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['pk'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='media',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
    ]
