# Generated by Django 5.0.3 on 2024-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cars')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.DateField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Cars',
                'verbose_name_plural': 'Cars',
                'db_table': 'Cars',
            },
        ),
    ]
