# Generated by Django 5.0.3 on 2024-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
