# Generated by Django 5.0.3 on 2024-04-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0002_alter_cars_name_alter_cars_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='make',
            new_name='car_make',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='price',
            new_name='car_price',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='year',
            new_name='car_year',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_view_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Views count'),
        ),
    ]
