# Generated by Django 5.0.3 on 2024-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0003_rename_make_cars_car_make_rename_name_cars_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price'),
        ),
    ]
